sudo: false
language: node_js
# cache:
#     directories:
#         - node_modules
notifications:
    email: false
node_js:
    - 10
before_install:
    - npm i -g npm@^6.13.7
before_script:
    - npm prune
script:
    - npm run test:single
    - npm run check-coverage
after_success:
    - npm run report-coverage
    - npm run semantic-release